src/backend/core/models.py
src/backend/core/tests/authentication/test_backends.py
src/backend/core/tests/items/test_api_items_children_create.py
src/backend/core/tests/items/test_api_items_create.py
src/backend/core/tests/test_models_invitations.py

We have a race condition when several items are created at the same time. To avoid this race condition, we lock the Item table in ROW EXCLUSIVE MODE when calling the child creation.
Fixes #70

🐛(back) concurrency issues while creating item

---

src/backend/core/api/viewsets.py
src/backend/core/factories.py
src/backend/core/tests/items/test_api_items_media_auth.py

In the media_auth endpoint we are not checking if the item is a file and its upload_state is uploaded. We must check this to avoid unwanted behavior like trying to access a media before it should be.

🐛(back) check if an item is a file and uploaded in media_auth route

---

src/frontend/apps/drive/src/features/explorer/components/ExplorerDndProvider.tsx
src/frontend/apps/drive/src/features/explorer/components/ExplorerInner.tsx
src/frontend/apps/drive/src/features/explorer/components/grid/ExplorerGrid.tsx
src/frontend/apps/drive/src/features/explorer/components/modals/ExplorerRenameItemModal.tsx
src/frontend/apps/drive/src/features/explorer/components/tree/ExplorerTree.tsx
src/frontend/apps/drive/src/features/explorer/components/tree/ExplorerTreeItem.tsx
src/frontend/apps/drive/src/features/explorer/components/tree/ExplorerTreeItemActions.tsx
src/frontend/apps/drive/src/features/i18n/translations.json

- The item in which we drop an item remains in its surrounded version and with its border after having dropped
- We get the workspace menu when clicking on "..." of a folder
- translations for explorer actions
- Can't select range + ctrl key #150

🐛(frontend) many fix before prod

---

src/backend/core/models.py
src/backend/core/tests/items/test_api_items_move.py

The children were not moved with their parents. It was caused by a wrong reassignement of the path of the children, we should replace the whole previous path with the new one.

🐛(back) fix move folder

---

src/frontend/apps/drive/src/features/explorer/components/ExplorerDndProvider.tsx
src/frontend/apps/drive/src/features/explorer/components/grid/ExplorerGrid.tsx
src/frontend/apps/drive/src/features/explorer/components/tree/ExplorerTree.tsx
src/frontend/apps/drive/src/features/explorer/hooks/useUpload.tsx

- Uploaded folders are show as leaf in the tree #165 
- It is possible to dnd a folder inside its own child #164

🐛(front) improve drag-and-drop validation

---

src/backend/core/api/__init__.py
src/backend/core/api/serializers.py
src/backend/core/api/viewsets.py
src/backend/core/models.py
src/backend/core/tests/items/test_api_item_accesses.py
src/backend/core/tests/items/test_api_item_accesses_create.py
src/backend/core/tests/items/test_api_item_invitations.py
src/backend/core/tests/items/test_api_item_upload_ended.py
src/backend/core/tests/items/test_api_items_children_create.py
src/backend/core/tests/items/test_api_items_children_list.py
src/backend/core/tests/items/test_api_items_create.py
src/backend/core/tests/items/test_api_items_delete.py
src/backend/core/tests/items/test_api_items_favorite.py
src/backend/core/tests/items/test_api_items_hard_delete.py
src/backend/core/tests/items/test_api_items_link_configuration.py
src/backend/core/tests/items/test_api_items_list_filters.py
src/backend/core/tests/items/test_api_items_move.py
src/backend/core/tests/items/test_api_items_restore.py
src/backend/core/tests/items/test_api_items_retrieve.py
src/backend/core/tests/items/test_api_items_update.py
src/backend/core/tests/test_api_users.py
src/backend/core/tests/test_models_items.py
src/backend/drive/settings.py
src/backend/drive/urls.py
src/backend/pyproject.toml

Add standardized error codes for 40x responses
Proper handling of 40x error responses by the frontend requires machine codes.
DRF only returns a human readable message by default by we can rely on the standardized_errors package mentioned in DRF documentation.

Add codes to validation errors

---

src/backend/drive/urls.py

The debug_toolbar package is now a dev dependency. So the module can't be imported in other environment than the dev one. To avoid missing module error, we import it only in debug mode.

🐛(back) import debug_toolbar_urls only in debug mode

---

src/frontend/apps/drive/src/features/ui/components/responsive/ResponsiveDivs.tsx

This function is not available on Firefox, so I decided to switch to getComputedStyle that seem to achieve the same result.

🐛(front) fix computedStyleMap usage

---

bin/Tiltfile
src/backend/core/models.py
src/backend/core/tests/items/test_api_items_restore.py
src/backend/core/tests/test_models_items.py

When an item is restored and has ancestors deleted, instead of restoring it at its initial depth, we move it in the top level workspace.
Fix #158

♻️(back) restore item with ancestors deleted in the highest ancestor

---

src/backend/core/api/viewsets.py
src/backend/core/models.py
src/backend/core/tests/items/test_api_item_accesses_create.py
src/backend/core/tests/items/test_api_item_invitations.py
src/backend/locale/fr_FR/LC_MESSAGES/django.po

The link in the link was not correct, also added french translation for the sent mails. The language used was not the language of the user, I replaced with the most up to date approach used on Docs.

🐛(back) fix mail language and url

---

src/backend/core/authentication/backends.py
src/backend/core/authentication/views.py
src/backend/core/tests/authentication/test_backends.py
src/backend/core/tests/authentication/test_views.py
src/backend/drive/settings.py
src/frontend/Dockerfile

During the refacto replacing the usage of mozillaOIDC library to django lasuite library, I removed the usage of postog allowing to filter to a limited list of the user the access to posthog. This PR revert this removal and integrates it with django lasuite

⏪️(back) use posthog with django lasuite integration

---

Procfile
bin/scalingo_postcompile
bin/scalingo_postfrontend
bin/scalingo_run_web
src/backend/drive/settings.py
src/backend/pyproject.toml
src/frontend/apps/drive/package.json
src/frontend/apps/drive/src/features/explorer/components/Explorer.tsx
src/frontend/package.json
src/nginx/servers.conf.erb

This commit, with contributions from @sylvaingi , adds support for PaaS deployment platforms such as Scalingo, which build the project on commit. It uses the La Suite Buildpack, which compiles the frontend first as static files, and serves them along with the backend with nginx.
Squashed from #152

🚀(scalingo) add Scalingo deployment scripts and fix frontend build

---

src/backend/drive/settings.py

The settings CORS_ALLOW_ALL_ORIGINS was set to True by default.
This error is inherited from a old mistake made back in the days while working on the initial impress demo.
This is not something we want, this should be only allowed in development. We change the value in all the manifests in order to have the desired behavior in non development environments.

🩹(backend) default CORS_ALLOW_ALL_ORIGINS to False

---

CHANGELOG.md
src/backend/core/api/utils.py
src/frontend/apps/drive/src/features/drivers/implementations/StandardDriver.ts

When requesting file from the Scaleway object storage the Content-Type in the response header contain value like `multipart/form-data; boundary=----WebKitFormBoundaryP....` instead of expected values containing mime type like `application/pdf`. 
This was causing issue when previewing pdf, it was triggering a download instead of the browser native preview. 
This was only happening on Scaleway object storage, it is totally fine with MinIO which seems to guess itself the Content-Type based on Claude conversation. 
In its example here ( https://www.scaleway.com/en/docs/object-storage/api-cli/post-object/#examples ) we need to include Content-Type in the form data fields BEFORE ( ⚠️⚠️⚠️⚠️ ) the `file` field ( otherwise it doesn't work ) and also include a blank condition `["starts-with", …

🐛(global) fix wrong Content-Type on specific s3 implementations

---

CHANGELOG.md
bin/scalingo_pgdump.sh
cron.json

add scalingo_pgdump script to dump the database and upload it to scaleway s3.
add cron.json to schedule pgdump everyday at noon UTC.

🔧(cron): add pgdump cron on scalingo deployment

---

compose.yaml
docker/auth/realm.json

Set `sslRequired` to `none` for all realms in the keycloak dev service. By default this settings is set to `external` and only local IPs are granted to access to the server without SSL. But sometimes, with docker (desktop?) it appears the network configuration may keycloak to consider the accessing ip as not local.
We also took opportunity of this change to use the latest keycloak image version

🧑‍💻(keycloak) do not require ssl for dev server

---

CHANGELOG.md
src/frontend/apps/drive/conf/default.conf
src/nginx/servers.conf.erb

The previous fix was missing to explorer part.

🔧(nginx) fix trash route

---

CHANGELOG.md
src/frontend/apps/drive/src/features/explorer/components/modals/share/WorkspaceShareModal.tsx

Update the left tree in order to get the most up to date field value possible. It was keeping the old value when reopening the modal.

🐛(front) fix workspace link react cache

---

CHANGELOG.md
src/backend/core/api/serializers.py
src/backend/core/tests/items/test_api_items_update.py

Partially updating an item without specifying the title in the payload was always failing for item with a depth higher than 1. This is because the title is "sanitize" on a None value. To fix this, this sanitization is not made if the title is not sent in the payload.

🐛(backend) allow item partial update without modifying title

---

.github/workflows/crowdin_upload.yml
.github/workflows/drive.yml

The setup-python action is able to cache the dependencies and reuse this
cache while the pyproject file has not changed. It is easy to setup,
juste the package manager used has to be declared in the cache settings.

⚡️(ci) use setup-python cache option

---

.github/workflows/docker-hub.yml

Replace custom Docker Hub authentication with standard, secure, official GitHub actions for improved security and maintainability.
Uses officially supported actions that follow security best practices and receive regular updates from GitHub.
Avoid unsecure handling of GitHub secrets.

🔧(ci) refactor Docker Hub login to use official GitHub actions

---

.github/workflows/drive.yml

git-lint steps are independant and we would like to have all checks at once. Using the `if: always()` instruction should ensure all steps should be run event if the previous fails.

🔧(ci) always run all git-lint steps

---

CHANGELOG.md
src/frontend/apps/drive/src/features/explorer/components/app-view/AppExplorerGrid.tsx
src/frontend/apps/drive/src/features/explorer/components/app-view/AppExplorerInner.tsx

Changed the return value of the folders variable from an empty array to undefined when there are no children items. Additionally, added a guard clause in the useEffect to prevent execution if folders is undefined.
close #268

🐛(front) fix folders return value in AppExplorerGrid
