- src/frontend/apps/drive/conf/default.conf
fix nginx config to match drive architecture
> 🔧(front) fix nginx config to match drive architecture

- src/frontend/apps/drive/src/pages/index.scss
I forgot the set the height on the element, it was causing a double scroll bar. I also did a bit a refactor to avoid code duplication.
> 🐛(front) fix double scroll on home page

- src/frontend/apps/drive/src/features/explorer/components/ExplorerDndProvider.tsx
- src/frontend/apps/drive/src/features/explorer/components/toasts/addItemsMovedToast.tsx
- src/frontend/apps/drive/src/features/explorer/components/tree/ExplorerTree.tsx
- src/frontend/apps/drive/src/features/i18n/translations.json
We want the app to give feedback to the users.
Fixes #92
> ✨(front) add toast on moved items

- src/backend/core/api/viewsets.py
- src/backend/core/tests/items/test_api_items_trashbin.py
We need to filter also on this specific route according to the sketches.
> ✨(back) add filtering on trash route

- src/frontend/apps/drive/package.json
- src/frontend/apps/drive/src/features/drivers/Driver.ts
- src/frontend/apps/drive/src/features/drivers/implementations/StandardDriver.ts
- src/frontend/apps/drive/src/features/explorer/components/Explorer.scss
- src/frontend/apps/drive/src/features/explorer/components/Explorer.tsx
- src/frontend/apps/drive/src/features/explorer/components/ExplorerFilters.tsx
- src/frontend/apps/drive/src/features/explorer/components/ExplorerInner.tsx
- src/frontend/apps/drive/src/features/explorer/hooks/useMutations.ts
- src/frontend/apps/drive/src/features/explorer/hooks/useTableKeyboardNavigation.ts
- src/frontend/apps/drive/src/features/i18n/translations.json
- src/frontend/apps/drive/src/pages/explorer/items/[id].tsx
- src/frontend/apps/drive/src/pages/explorer/trash/index.tsx
- src/frontend/yarn.lock
> Add minimal filters

- src/frontend/apps/drive/src/features/explorer/components/Explorer.tsx
- src/frontend/apps/drive/src/features/explorer/components/grid/ExplorerGrid.tsx
- src/frontend/apps/drive/src/features/i18n/translations.json
- src/frontend/apps/drive/src/pages/explorer/trash/index.tsx
- src/frontend/apps/drive/src/pages/index.scss
To avoid various issue this is the best short term solution. We also notice that other main drive tool on the market do the same thing.
> ✨(front) disable navigation in trash

- src/frontend/apps/drive/src/features/explorer/components/modals/ExplorerCreateFolderModal.tsx
- src/frontend/apps/drive/src/features/explorer/components/tree/ExplorerTree.scss
- src/frontend/apps/drive/src/features/explorer/components/tree/ExplorerTree.tsx
- src/frontend/apps/drive/src/features/explorer/components/tree/ExplorerTreeItemActions.tsx
> ✨(front) add menu to create a child folder from the tree + 🐛(front) fix tree item text ellipsis

- src/backend/core/api/serializers.py
- src/backend/core/tests/items/test_api_items_children_list.py
- src/backend/core/tests/items/test_api_items_favorite_list.py
- src/backend/core/tests/items/test_api_items_list.py
- src/backend/core/tests/items/test_api_items_retrieve.py
- src/backend/core/tests/items/test_api_items_trashbin.py
- src/backend/core/tests/items/test_api_items_tree.py
We need this field on frontend to be able to perform some redirection based on it, if an item is soft deleted we want to redirect.
> ✨(back) add deleted_at field to items

- CHANGELOG.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
So that we provide guidelines to the community
> 📝(doc) add code of conduct.md, changelog.md and contributing.md

- src/frontend/apps/drive/package.json
- src/frontend/apps/drive/src/features/auth/components/LogoutButton.tsx
- src/frontend/apps/drive/src/features/explorer/components/Explorer.scss
- src/frontend/apps/drive/src/features/explorer/components/Explorer.tsx
- src/frontend/apps/drive/src/features/explorer/components/ExplorerBreadcrumbs.tsx
- src/frontend/apps/drive/src/features/explorer/components/ExplorerContext.tsx
- src/frontend/apps/drive/src/features/explorer/components/ExplorerInner.tsx
- src/frontend/apps/drive/src/features/explorer/components/ExplorerSearchButton.tsx
- src/frontend/apps/drive/src/features/explorer/components/grid/ExplorerGrid.tsx
- src/frontend/apps/drive/src/features/explorer/components/grid/ExplorerGridMobileCell.tsx
- src/frontend/apps/drive/src/features/explorer/components/tree/ExplorerTree.scss
- src/frontend/apps/drive/src/features/explorer/components/tree/ExplorerTree.tsx
- src/frontend/apps/drive/src/features/explorer/components/tree/ExplorerTreeActions.tsx
- src/frontend/apps/drive/src/features/explorer/components/tree/ExplorerTreeItem.tsx
- src/frontend/apps/drive/src/features/layouts/components/explorer/ExplorerLayout.tsx
- src/frontend/apps/drive/src/features/layouts/components/header/Header.tsx
- src/frontend/apps/drive/src/features/layouts/components/header/index.scss
- src/frontend/apps/drive/src/features/ui/components/responsive/ResponsiveDivs.tsx
- src/frontend/apps/drive/src/features/ui/components/responsive/index.scss
- src/frontend/apps/drive/src/styles/globals.scss
- src/frontend/yarn.lock
> ✨(front) make minimal responsive version for Alpha

- src/backend/core/authentication/backends.py
- src/backend/core/authentication/exceptions.py
- src/backend/core/authentication/views.py
- src/backend/core/tests/authentication/test_views.py
- src/backend/drive/settings.py
- src/backend/pyproject.toml
- src/frontend/apps/drive/src/features/i18n/translations.json
- src/frontend/apps/drive/src/pages/index.tsx
In order to be able to allow specific users during the alpha we need to add its support to the app.
> ✨(global) add posthog whitelisting feature

- .github/workflows/drive-frontend.yml
- src/frontend/Dockerfile
- src/frontend/apps/drive/eslint.config.mjs
- src/frontend/apps/drive/src/features/explorer/components/ExplorerBreadcrumbs.tsx
- src/frontend/apps/drive/src/features/explorer/components/ExplorerFilters.tsx
- src/frontend/apps/drive/src/features/explorer/components/ExplorerInner.tsx
- src/frontend/apps/drive/src/features/explorer/components/modals/ExplorerCreateFolderModal.tsx
- src/frontend/package.json
Before we were working like unstoppable high speed train, now it's time add more safety. :)
> 💚(ci) enable frontend CI

- .gitlint
- gitlint/gitlint_emoji.py
Add missing .gitlin config file
> 🔧(misc) add .gitlint config file

- src/frontend/apps/drive/src/features/i18n/translations.json
- src/frontend/apps/drive/src/pages/_app.tsx
We need to be able to customize the app title based on the language.
> 🐛(front) make the app title i18n

- src/frontend/apps/drive/src/features/i18n/translations.json
We need to update the wording to improve readability for users.
> 💬(front) update feedback texts

- CHANGELOG.md
- Makefile
- bin/update_openapi_schema
- src/backend/drive/celery_app.py
- src/backend/pyproject.toml
- src/frontend/apps/sdk-consumer/package.json
- src/frontend/packages/sdk/package.json
- src/helm/drive/Chart.yaml
- src/helm/helmfile.yaml
- src/mail/package.json
- 🚀 Drive, A collaborative file sharing and document management platform
- ✨(front) add move modal #213
- ✨(front) update the homepage to alpha #234
- ✨(global) add customization to feedbacks
- ✨(front) add PDF, Audio, Video, Image viewers
- ✨(front) make frontend themable
- ✨(global) Add File Picker SDK
- 🔧(cron) add pgdump cron on scalingo deployment #264
- 🐛(email) add missing email logo
- 🐛(i18n) fix language detection and rendering
- 🌐(front) add english translation for rename modal
- 🐛(global) fix wrong Content-Type on specific s3 implementations
>  🔖(minor) bump release version 0.1.0

- .github/workflows/drive-frontend.yml
- CHANGELOG.md
- Makefile
- bin/clear_db_e2e.sql
- bin/postgres_e2e
- compose.yaml
- env.d/development/postgresql.e2e
- src/backend/drive/settings.py
- src/backend/drive/urls.py
- src/backend/e2e/serializers.py
- src/backend/e2e/tests/test_api_e2e.py
- src/backend/e2e/urls.py
- src/backend/e2e/viewsets.py
- src/frontend/apps/e2e/.gitignore
- src/frontend/apps/e2e/__tests__/app-drive/create-folder.spec.ts
- src/frontend/apps/e2e/__tests__/app-drive/db.setup.ts
- src/frontend/apps/e2e/__tests__/app-drive/login.spec.ts
- src/frontend/apps/e2e/__tests__/app-drive/utils-common.ts
- src/frontend/apps/e2e/package.json
- src/frontend/apps/e2e/playwright.config.ts
- src/frontend/apps/e2e/tsconfig.json
- src/frontend/yarn.lock
Just run
```
make run-tests-e2e
```
It will:
- Start the backend with the e2e db
- Clear the DB
- Apply migrations
- Run the e2e tests on it
You can also pass parameters like so:
```
make run-tests-e2e -- --project chromium --headed
```
After the run the backend will still run on the e2e DB without clearing, this is on purpose in case you need to interact with the state of the app after the tests have run or failed, in order to update them.
> ✅(front) add e2e tests

- CHANGELOG.md
- src/frontend/apps/drive/src/features/explorer/components/GlobalExplorerContext.tsx
- src/frontend/apps/drive/src/features/explorer/components/app-view/AppExplorerBreadcrumbs.tsx
- src/frontend/apps/drive/src/features/explorer/components/embedded-explorer/EmbeddedExplorerGridActionsCell.tsx
- src/frontend/apps/drive/src/features/explorer/components/embedded-explorer/EmbeddedExplorerGridBreadcrumbs.tsx
- src/frontend/apps/drive/src/features/explorer/components/tree/ExplorerTreeItem.tsx
- src/frontend/apps/drive/src/features/explorer/components/tree/ExplorerTreeItemActions.tsx
- src/frontend/apps/drive/src/features/explorer/components/tree/hooks/useDeleteTreeNode.tsx
- src/frontend/apps/drive/src/features/explorer/hooks/useDeleteItem.tsx
- src/frontend/apps/drive/src/features/explorer/utils/utils.ts
- src/frontend/apps/drive/src/features/i18n/translations.json
- src/frontend/apps/e2e/__tests__/app-drive/delete-item-in-tree.spec.ts
- src/frontend/apps/e2e/__tests__/app-drive/utils-common.ts
- src/frontend/apps/e2e/__tests__/app-drive/utils-explorer.ts
- src/frontend/apps/e2e/__tests__/app-drive/utils-item.ts
- src/frontend/apps/e2e/__tests__/app-drive/utils-tree.ts
> 🐛(front) fix redirect after delete node in tree

- CHANGELOG.md
- src/backend/core/api/filters.py
- src/backend/core/api/permissions.py
- src/backend/core/api/serializers.py
- src/backend/core/api/viewsets.py
- src/backend/core/migrations/0013_active_unnaccent_postgres_extension.py
- src/backend/core/tests/items/test_api_items_search.py
- src/backend/drive/settings.py
We need a new endpoint for the search feature. Using existing filters on the list or children endpoint does not match what we want. We want to search for all accessible items for the current user.
Part of #279
> ✨(backend) search endpoint for ItemViewSet

- CHANGELOG.md
- src/frontend/apps/drive/src/features/explorer/components/GlobalExplorerContext.tsx
- src/frontend/apps/drive/src/features/explorer/components/embedded-explorer/EmbeddedExplorerGridActionsCell.tsx
- src/frontend/apps/drive/src/features/explorer/components/right-panel/ExplorerRightPanelContent.tsx
- src/frontend/apps/e2e/__tests__/app-drive/item/right-content-info.spec.ts
- src/frontend/apps/e2e/__tests__/app-drive/utils-embedded-grid.ts
when we opened the right panel, we did not arrive at the right item
> 🐛(front) fix the content when opening the right panel

- CHANGELOG.md
- Procfile
Description...
Description...
- [] item 1...
- [] item 2...
> 🔧(procfile) added celery worker on scalingo deployment
